bloom-housing/ui-seeds

- src/blocks/Card.scss
- src/blocks/Card.tsx
- src/blocks/__stories__/Card.docs.mdx
- src/blocks/__stories__/Card.stories.tsx
This PR addresses #35 and #37 
The spacing options for Card have been redone to use regular "t-shirt" sizes.
The stories were also updated to use the HeadingGroup component.
Storybook examples: https://deploy-preview-38--storybook-ui-seeds.netlify.app/?path=/story/blocks-card--spacings
> chore: update Card spacings and use HeadingGroup in stories

- src/expandableText/ExpandableText.tsx
This PR is a fix to address broken tests in Bloom when attempting to pull in a component from ui-seeds. This has been fixed in other cases by adding the [React import explicitly ](https://stackoverflow.com/questions/64656055/react-refers-to-a-umd-global-but-the-current-file-is-a-module).
> fix: add react import to expandabletext

- src/blocks/shared/CommonMessage.tsx
This PR partially addresses https://github.com/bloom-housing/bloom/issues/3434
As part of the uptake, I noticed that the toast component would still render without a message defined and required me to write out successToastMessage && <Toast>{successToastMessage}</Toast> for every instance. This change should help reduce clutter in uptake across all message types and preserve the intention of conveying a message.
This can be tested by starting up the storybook and removing the children to any component that extends common message and it will not render as opposed to rendering empty.
> fix: prevent empty messaging

- src/navigation/Tabs.scss
- src/navigation/__stories__/Tabs.docs.mdx
This PR addresses #55 
The text size of small tabs should be smaller (right?) than the normal tabs. That wasn't the case once the global semantic text size tokens got renamed, so this fixes it.
Normal tabs: https://deploy-preview-56--storybook-ui-seeds.netlify.app/?path=/story/navigation-tabs--default
Small tabs: https://deploy-preview-56--storybook-ui-seeds.netlify.app/?path=/story/navigation-tabs--small-tabs
> fix: text size tokens for Tabs

- src/actions/Button.scss
- src/actions/Button.tsx
- src/actions/__stories__/Button.stories.tsx
This PR addresses QA feedback as noted in #36 
The `borderless-text` variant has been renamed to `text`, and padding has been removed. There's also just small and medium sizes now (specifying a large size will look identical to medium).
Storybook: https://deploy-preview-58--storybook-ui-seeds.netlify.app/?path=/story/actions-button--text-buttons
> fix: update `text` variant of Button to align with design

- src/actions/Button.scss
This is just a couple of small CSS fixes for the `Button` component as I ran into issues with full-width button update in Core.
https://deploy-preview-61--storybook-ui-seeds.netlify.app/
(this should look the same as before, but if you were to edit one of the buttons in browser dev tools to be a specific width like 500px, you'll see that the button is exactly 500px and the text/icon inside is centered)
> fix: flex justification and sizing on Button

- src/layout/Grid.scss
- src/layout/__stories__/Grid.docs.mdx
- src/layout/__stories__/Grid.stories.tsx
- src/text/HeadingGroup.scss
- src/text/__stories__/HeadingGroup.docs.mdx
This PR addresses feedback based on design QA and on uptake issues related to:
https://github.com/bloom-housing/bloom/pull/3643
Several changes are involved (and we'll want to update zero height accordingly post-merge):
* The previous "1+2" and "2+1" columns stuff didn't really make sense in light of how the grids were working in the Partners site. It makes more sense to specify that certain cells can span 2 or 3 of the grid columns. This includes utility classes for that purpose. (They're not done via props because multiple types of components can serve as grid cells.)
* Medium-size screens (like tablets) should limit the total number of columns to two, so this was done on a cell-width basis in CSS.
* Medium screen grids should show medium grid gap (and mobile is still small gap).
* …
> chore: adjust Grid and HeadingGroup spacings and behavior

- src/actions/Button.scss
- src/actions/Button.tsx
- src/actions/__stories__/Button.stories.tsx
This PR addresses #64 
This PR adds a `loadingMessage` prop which will display a loading spinner, make clicks disabled, and also announce an ARIA live message.
This Storybook example:
https://deploy-preview-67--storybook-ui-seeds.netlify.app/?path=/story/actions-button--loading-button
> chore: loading state for Button

- src/hooks/useTimeout.ts
The `shared-helpers` linter in the core Bloom repo was failing due to an implicit return in Seeds' `useTimeout` hook. This adds an explicit return so that the linter will be happy.
I tested the fix in the local `node_modules` copy of ui-seeds and the shared-helpers Jest tests passed.
> fix: make TS happy with explicit return

- LICENSE.txt
- README.md
- src/blocks/Card.scss
This PR addresses #40 
An Apache license is now included just like in other Bloom repos, and a Readme now features preliminary documentation around how the styles and React components should be set up along with info on Storybook and zeroheight.
Feedback and more ideas of what to include most welcome!
(Also I found a couple of design tokens for Card I could replace with semantic equivalents...visual appearance should be identical.)
> docs: add license and readme

- src/blocks/Toast.scss
- src/blocks/__stories__/Toast.docs.mdx
- src/blocks/__stories__/Toast.stories.tsx
Based on feedback from Toast uptake (see https://github.com/bloom-housing/bloom/pull/3553), this fixes a few size/spacing issues.
In the Toast examples, you'll see that the width resizes to the length of text (up to a certain point, then it starts to wrap). And the top/right page space has been bumped up a size token.
> fix: improvements to Toast sizes and spacing

- src/navigation/Tabs.scss
- src/navigation/__stories__/Tabs.docs.mdx
This PR partially addresses #73
This PR allows for the tab orientation breakpoint to be overridden by a consumer. It is a temporary fix to allow for the tab component to be displayed vertically on all screen sizes.
This can be tested by adding "@custom-media --tab-collapse-breakpoint (max-width: 10000px);" to the tabs-tablist class to show it can be overriden.
> fix: temp vertical tabs

- src/blocks/__stories__/Alert.stories.tsx
- src/blocks/__tests__/CommonMessage.test.tsx
- src/blocks/shared/CommonMessage.tsx
This PR addresses #80 
You can now pass an `onClose` prop with a callback to any of the CommonMessage components (Alert, Message, and Toast—but this is primarily for use with Alert).
There's an example in Storybook here: https://deploy-preview-81--storybook-ui-seeds.netlify.app/?path=/story/blocks-alert--wide-container-layout
> feat: add onClose feature to CommonMessage

- src/actions/Button.tsx
- src/actions/__stories__/Button.stories.tsx
This PR addresses #76 
ARIA features that had been added before to UI Components Button were missing from Seeds. This PR adds those in.
Storybook: https://deploy-preview-78--storybook-ui-seeds.netlify.app/?path=/story/actions-button--expanding-button
> feat: add support for `aria-expanded` to Seeds button

- package.json
- src/actions/Button.scss
- src/actions/Button.tsx
- src/actions/Link.scss
- src/actions/Link.tsx
- src/actions/__stories__/Button.docs.mdx
- src/actions/__stories__/Button.stories.tsx
- src/actions/__stories__/Link.docs.mdx
- src/actions/__stories__/Link.stories.tsx
- src/actions/__tests__/Button.test.tsx
- src/actions/__tests__/Link.test.tsx
- src/blocks/Alert.scss
- src/blocks/Message.scss
- src/blocks/Toast.scss
- src/blocks/__stories__/Alert.docs.mdx
- src/blocks/__stories__/Alert.stories.tsx
- src/blocks/__stories__/Message.docs.mdx
- src/blocks/__stories__/Message.stories.tsx
- src/blocks/__stories__/Toast.docs.mdx
- src/blocks/__tests__/CommonMessage.test.tsx
- src/blocks/shared/CommonMessage.scss
- src/blocks/shared/CommonMessage.tsx
- src/icons/Icon.scss
- src/icons/Icon.tsx
- src/icons/__stories__/Icon.stories.tsx
- src/icons/__tests__/Icon.test.tsx
- src/overlays/Overlay.tsx
- src/text/Tag.scss
- src/text/__stories__/Tag.stories.tsx
- yarn.lock
This PR addresses #69 
This PR swaps out FontAwesome icons inside of various Seeds components with Hero Icons. In addition, it makes some adjustments to icon sizes (and introduces a "scale factor" option for consumers in case they have other custom icon requirements) to accomodate this change.
The Icon component also offers a new `outlined` prop which adds better support for coloring outlined SVGs as opposed to solid SVGs.
Check out the Icon stories as well as other components which offer icons or can display icons such as Alert, Button, Dialog, Drawer, Link, Message, Tag, Toast.
> feat: adopt Hero Icons as replacement for FontAwesome

- src/global/text.scss
- src/overlays/Dialog.tsx
- src/overlays/Drawer.tsx
- src/overlays/Overlay.scss
- src/overlays/Overlay.tsx
- src/overlays/__mocks__/tabbable.js
- src/overlays/__stories__/Dialog.stories.tsx
- src/overlays/__stories__/Drawer.stories.tsx
This PR addresses #84 
Adds support for additional ARIA attributes useful for modal content, and made some tweaks to focus trapping so it's working across browsers (at least on macOS).
View the Dialog: https://deploy-preview-85--storybook-ui-seeds.netlify.app/?path=/story/overlays-dialog--default
and Drawer: https://deploy-preview-85--storybook-ui-seeds.netlify.app/?path=/story/overlays-drawer--default
and try out using a screen reader like VoiceOver in various browsers.
My goal was to make sure the Dialog is announced with the heading having focus, and then you can move ahead to the Close button and additional content. Drawer is a little tricky here because the Close button comes first visually, so I actually modified it so it always comes after the heading in source order, but things …
> feat: various ARIA enhancements for Overlay (Dialog & Drawer)

- src/forms/CheckboxGroup.tsx
This fixes a relative path to the Button component from within CheckboxGroup—otherwise the Next.js apps won't build.
> fix: relative path to Button [URGENT]

- src/overlays/Overlay.tsx
Sets a fallback focus on our Overlay / Dialog components - tests fail without this, and it's a good thing to have on anyway for a11y in case the content doesn't load!
> fix: update fallback focus on overlay

- src/navigation/Tabs.scss
- src/navigation/Tabs.tsx
- src/navigation/__stories__/Tabs.docs.mdx
- src/navigation/__stories__/Tabs.stories.tsx
This PR addresses #79 
This adds a feature to specify a vertical tabs sidebar layout. It will show a list of tabs on the left and the active panel on the right. On mobile displays, the tabs & panel will collapse to a single column just as before.
View the story here: https://deploy-preview-91--storybook-ui-seeds.netlify.app/?path=/story/navigation-tabs--vertical-tabs
> feat: add vertical tabs with sidebar layout

- src/overlays/Dialog.scss
- src/overlays/Drawer.scss
- src/overlays/Overlay.scss
This PR updates full-height and width UX to use dynamic viewport height / width, while still having the existing 100vh or 100vw as a backup. Without this, depending on the mobile browser you use, the URL box can overlap page content.
Example from Doorway production - I can't scroll down to the sticky footer.
I wasn't able to reproduce this in Storybook, but adding this in Doorway fixed it over there!
> fix: dynamic height and width

- src/global/app-css.scss
- src/global/spacing.scss
This PR addresses #100
In the process of uptaking seeds in core, we're having to add classes to module files just to add a single style like a bottom margin. These are the only kinds of styles we're experiencing this with. These new classes use both our semantic and global tokens for seeds spacings.
I don't think we generally want to follow this pattern to avoid where we can the inline messiness we experienced with Tailwind, but I think for now just spacings would be really helpful.
I have self-assigned a followup ticket to add this into Zeroheight documentation after merge: https://github.com/bloom-housing/ui-seeds/issues/101
> feat: spacing token classes

- src/global/tokens/colors.scss
We had two tokens where we were using core colors instead of semantic tokens.
This updates to use the semantic tokens.
The values didn't change in core.
> fix: move to semantic tokens for bg colors

- src/actions/Button.scss
This PR addresses #109
In essence we want the button hover state only when fine pointers are used (aka a mouse cursor, but also a stylus with hovering support like Apple Pencil).
Verify that when you're using touchscreen devices, there's no hover state activated for a button upon tap. But hover still works when using a mouse or stylus.
> fix: show button hover only on fine pointer devices

- .storybook/main.js
- package.json
- src/actions/Button.scss
- src/blocks/Card.scss
- src/blocks/Toast.scss
- src/navigation/Tabs.scss
- src/overlays/Overlay.scss
- src/text/ExpandableText.scss
- src/theming/__stories__/Theming.stories.tsx
- yarn.lock
Adds RTL addon support into Storybook, and transitions some of our remaining classes to logical spacings.
In a story, there's now a blue arrow icon in the toolbar that will swap a story into RTL mode.
The main component with a RTL issue was the Tabs component, so you can check out [that component in Storybook](https://deploy-preview-113--storybook-ui-seeds.netlify.app/?path=/story/navigation-tabs--small-tabs) in RTL mode as well!
> fix: rtl support

- package.json
- src/overlays/Overlay.tsx
- yarn.lock
This PR addresses part of https://github.com/bloom-housing/bloom/issues/4777
This upgrades the focus-trap-react package and the overlay component with some minor tweaks
Attempting to upgrade nextjs required this package get upgraded so upgraded it now is
you should be able to stand this up locally and look around the overlay components and see that they are exactly the same as they were before
> feat: upgrading focus-trap-react

- src/navigation/Tabs.scss
This PR lowers the font weight for unselected tabs to more closely match the latest [designs](https://www.figma.com/design/xqyamlgdsASkLTYlcifBwq/core-patterns?node-id=2133-50445&m=dev).
You can check out the [Tabs stories](https://deploy-preview-116--storybook-ui-seeds.netlify.app/?path=/story/navigation-tabs--default).
> fix: lower font weight for unselected tab

- src/overlays/__stories__/Dialog.stories.tsx
Adds [an additional story to the Dialog component](https://deploy-preview-112--storybook-ui-seeds.netlify.app/?path=/story/overlays-dialog--full-width-video) to demonstrate how to support a full width video. We need this behavior [in Detroit](https://homeconnect.detroitmi.gov/housing-basics).
Check out the story! The styles and overrides added are visible in the code sample below the story.
If there's a preference to have this be a flag on the modal, where you can pass in a video URL and it just does this - lmk!
> docs: video dialog story

- src/blocks/shared/CommonMessage.tsx
A followup for https://github.com/bloom-housing/ui-seeds/pull/122 
When there are no children, the message should visually hide altogether. This is the existing unwanted behavior:
I've since deleted it because I don't think we should publish it, but I created a story locally with a message with no children and ensured an empty div is rendered in the DOM.
> fix: hide message entirely if no children

- src/forms/FieldValue.tsx
- src/layout/Grid.tsx
- src/layout/__stories__/Grid.stories.tsx
Related to: https://github.com/bloom-housing/bloom/pull/5138
This PR fixes some a11y issues with the grid + related components. The way we're using our Grids causes page data to often read very strangely compared to what we're intending. It reads form fields and detail views with lots of extra and unhelpful information about rows and columns, but that information is actually not relevant to the data on the screen for any of our use cases. In research I'm also seeing `The grid role is best suited for applications where the grid itself is a primary interactive widget, such as a data grid or a spreadsheet-like interface, not just for displaying data that happens to be visually arranged in a grid.`
Because of this, I have made the default behavior of the Grid component to be not including the …
> fix!: grid role a11y fixes

- README.md
The GitHub action failed for releasing the [previous commit](https://github.com/bloom-housing/ui-seeds/commit/f7f0c50cd07ef032a28a9b4e868533ec0d60e3d3), so this PR includes a minor documentation update and should release both changes.
> feat: role a11y fixes, documentation

- src/text/HeadingGroup.tsx
This PR addresses [#4913](https://github.com/bloom-housing/bloom/issues/4913)
It's change needed for [this PR](https://github.com/bloom-housing/bloom/pull/5221) it will pass heading tab index and id from `HeadingGroup` to `Heading`
.
> fix: add heading id and tab index for HeadingGroup
